apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: ollama
  annotations:
    scenarios.ai.sap.com/description: "Run a ollama server on SAP AI Core"
    scenarios.ai.sap.com/name: "ollama"
    executables.ai.sap.com/description: "ollama service"
    executables.ai.sap.com/name: "ollama"
  labels:
    scenarios.ai.sap.com/id: "ollama"
    ai.sap.com/version: "0.0.1"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: infer.s
    spec: |
      predictor:
        imagePullSecrets:
          - name: "eyJhdXRocyI6eyJodHRwczovL2h1Yi5kb2NrZXIuY29tL3JlcG9zaXRvcnkvZG9ja2VyL3NvdWJoaWs4ODAvb2xsYW1hLyI6eyJ1c2VybmFtZSI6InNvdWJoaWs4ODAiLCJwYXNzd29yZCI6IlNvdWJoaWtAODgwIiwiZW1haWwiOiJzb3ViaGlrLmt1bmR1ODgwQGdtYWlsLmNvbSIsImF1dGgiOiJjMjkxWW1ocGF6ZzRNRHBUYjNWaWFHbHJRRGc0TUE9PSJ9fX0="
        minReplicas: 1
        maxReplicas: 1
        containers:
        - name: kserve-container
          image: docker.io/soubhik880/ollama:ai-core
          ports:
            - containerPort: 8080
              protocol: TCP

